server:
  port: 3344

spring:
  application:
    name: cloud-config-center     # 注册进eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/egbz/springcloud-config.git     # github上git仓库名
          #### 搜索目录
          search-paths:
            - springcloud-config
      #### 读取分支
      label: main


# 服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka