server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver     # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: nuaa1234
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样概率值介于0 到 1 之间, 1 表示全部采样
      probability: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.egbz.clouddemo.entity  # 所有entity别名类所在包

eureka:
  client:
    # 表示是否将自己注册进eureka server, 默认为true
    register-with-eureka: true
    # 是否从eureka server抓取已有的注册信息, 默认为true.单节点无所谓, 集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka, http://localhost:7002/eureka  # 集群版
      #      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true   # 访问路径可以显示ip地址
